export let seedPublications = [
  {
    id: 2,
    name: "Every Day",
    author: "Bill Granger",
    edition: null,
  },
  {
    id: 3,
    name: "No Time to Cook",
    author: "Donna Hay",
    edition: null,
  },
  {
    id: 4,
    name: "Delicious",
    author: "Various",
    edition: "August 2007",
  },
  {
    id: 6,
    name: "Delicious",
    author: "Various",
    edition: "February 2008",
  },
  {
    id: 7,
    name: "Delicious",
    author: "Various",
    edition: "April 2008",
  },
  {
    id: 8,
    name: "Delicious",
    author: "Various",
    edition: "October 2013",
  },
  {
    id: 9,
    name: "Delicious",
    author: "Various",
    edition: "April 2013",
  },
  {
    id: 10,
    name: "Simply Bill",
    author: "Bill Granger",
    edition: "NA",
  },
  {
    id: 5,
    name: "Delicious",
    author: "Various",
    edition: "September 2007",
  },
  {
    id: 11,
    name: "Bill's Open Kitchen",
    author: "Bill Granger",
    edition: "NA",
  },
  {
    id: 12,
    name: "Delicious",
    author: "Various",
    edition: "May 2007",
  },
  {
    id: 13,
    name: "Nigella Express",
    author: "Nigella Lawson",
    edition: "NA",
  },
  {
    id: 14,
    name: "Taste Online",
    author: "Various",
    edition: "NA",
  },
  {
    id: 15,
    name: "Delicious",
    author: "Various",
    edition: "July 2011",
  },
  {
    id: 16,
    name: "Delicious",
    author: "Various",
    edition: "May 2008",
  },
  {
    id: 17,
    name: "Delicious",
    author: "Various",
    edition: "May 2008",
  },
  {
    id: 18,
    name: "Healthy Food Guide",
    author: "Various",
    edition: "June 2011",
  },
  {
    id: 19,
    name: "Google Docs",
    author: "NA",
    edition: "NA",
  },
  {
    id: 20,
    name: "Healthy Recipes Blogs",
    author: "Unknown",
    edition: "NA",
  },
  {
    id: 21,
    name: "Delicious",
    author: "Various",
    edition: "March 2011",
  },
];
