export let seedRatings = [
  {
    id: 1,
    value: 4,
    title: "Yummy!",
    comments: "A consistent favourite",
    userId: "3",
    recipeId: 5,
  },
  {
    id: 3,
    value: 5,
    title: "K",
    comments: "Delicious!",
    userId: "4",
    recipeId: 10,
  },
  {
    id: 2,
    value: 3,
    title: "K",
    comments: "Best when baked in a convection oven setting.",
    userId: "4",
    recipeId: 5,
  },
  {
    id: 4,
    value: 4,
    title: "K",
    comments: "Quick and tasty everyday meal",
    userId: "4",
    recipeId: 6,
  },
  {
    id: 5,
    value: 3,
    title: "Tasty everyday meal",
    comments: "",
    userId: "4",
    recipeId: 7,
  },
  {
    id: 6,
    value: 3,
    title: "Very nice. Requires enough time to prepare.",
    comments: "",
    userId: "4",
    recipeId: 4,
  },
  {
    id: 7,
    value: 4,
    title: "Very nice. Company worthy.",
    comments: "",
    userId: "4",
    recipeId: 3,
  },
  {
    id: 8,
    value: 3,
    title: "Quite good",
    comments: "Good, quick pasta dish. Sauce quite strong.",
    userId: "3",
    recipeId: 9,
  },
  {
    id: 9,
    value: 4,
    title: "Yum",
    comments: "Very rich",
    userId: "4",
    recipeId: 16,
  },
  {
    id: 10,
    value: 4,
    title: "Quick and tasty",
    comments: "",
    userId: "4",
    recipeId: 9,
  },
  {
    id: 11,
    value: 3,
    title: "Easy and not a bad bread substitute",
    comments: "",
    userId: "3",
    recipeId: 20,
  },
  {
    id: 12,
    value: 5,
    title: "Yum diddly umptous!",
    comments: "",
    userId: "4",
    recipeId: 22,
  },
];
