export let seedRecipes = [
  {
    id: 2,
    name: "Steak with Cherry Tomatoes and Cannellini Beans",
    pageNumber: 66,
    publicationId: 2,
    tags: ["Beef", "Tomato", "Cannellini beans"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 4,
    name: "Chicken, Ham & Potato Pie",
    pageNumber: 62,
    publicationId: 4,
    tags: ["Chicken", "Potato", "Ham", "Cream", "Pastry"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 6,
    name: "Stir-fried Pork & Pickled Cucumber on Rice Noodles",
    pageNumber: 96,
    publicationId: 6,
    tags: ["Pork Mince", "Spring Onions", "Ginger", "Coriander"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 7,
    name: "Biryani-style Baked Chicken",
    pageNumber: 66,
    publicationId: 7,
    tags: ["Chicken", "Rice"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 9,
    name: "Spaghetti with lentil bolognaise",
    pageNumber: 40,
    publicationId: 8,
    tags: [
      "Pasta",
      "Cherry tomatoes",
      "lentils",
      "basil",
      "Cherry tomato pasta sauce",
    ],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 10,
    name: "Spiced pear, blueberry & almond shortcake",
    pageNumber: 70,
    publicationId: 9,
    tags: ["Pear", "blueberry", "lemon", "dessert", "bill granger"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 8,
    name: "Spaghetti with cherry tomatoes, ricotta, spinach & pecorino",
    pageNumber: 13,
    publicationId: 10,
    tags: ["Pasta", "Ricotta", "Cherry Tomato", "Oregano"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 5,
    name: "Banana Bread",
    pageNumber: 95,
    publicationId: 5,
    tags: ["Banana"],
    preparationTime: 30,
    cookingTime: 60,
  },
  {
    id: 11,
    name: "Chickpea stew with tomatoes & green chilli",
    pageNumber: 136,
    publicationId: 11,
    tags: [
      "Chickpeas",
      "Cherry tomato",
      "ginger",
      "garlic",
      "baby spinach",
      "green chilli",
    ],
    preparationTime: 20,
    cookingTime: 15,
  },
  {
    id: 12,
    name: "The best spaghetti carbonara",
    pageNumber: 76,
    publicationId: 12,
    tags: [
      "Pasta",
      "egg",
      "cream",
      "bacon",
      "pancetta",
      "Parmesan cheese",
      "garlic",
    ],
    preparationTime: 15,
    cookingTime: 15,
  },
  {
    id: 3,
    name: "Crunchy Parmesan-Crumbed Chicken",
    pageNumber: 128,
    publicationId: 3,
    tags: ["Chicken", "Parmesan Cheese"],
    preparationTime: 10,
    cookingTime: 15,
  },
  {
    id: 13,
    name: "Pollo Alla Cacciatora",
    pageNumber: 296,
    publicationId: 13,
    tags: ["chicken", "rosemary", "cannellini beans"],
    preparationTime: 15,
    cookingTime: 25,
  },
  {
    id: 14,
    name: "Cauliflower Mac and Cheese",
    url: "http://www.taste.com.au/recipes/39191/cauliflower+mac+n+cheese",
    pageNumber: 0,
    publicationId: 14,
    tags: ["Cauliflower", "cheese", "pasta"],
    preparationTime: null,
    cookingTime: null,
  },
  {
    id: 15,
    name: "Salmon risotto",
    pageNumber: 0,
    publicationId: 22,
    tags: [
      "Salmon",
      "peas",
      "asparagus",
      "onion",
      "butter",
      "oil",
      "arborio rice",
      "white wine",
      "chicken stock",
      "parmasean",
      "cream",
    ],
    preparationTime: 15,
    cookingTime: 40,
  },
  {
    id: 16,
    name: "Exceptionally good brownies",
    pageNumber: 101,
    publicationId: 15,
    tags: ["Chocolate", "dessert", "walnuts"],
    preparationTime: 20,
    cookingTime: 40,
  },
  {
    id: 17,
    name: "Best ever spaghetti cabonara",
    pageNumber: 76,
    publicationId: 16,
    tags: [
      "Pasta",
      "parmasean",
      "bacon",
      "cream",
      "egg",
      "mushroom",
      "parsley",
    ],
    preparationTime: 20,
    cookingTime: 15,
  },
  {
    id: 18,
    name: "Best ever spaghetti cabonara",
    pageNumber: 76,
    publicationId: 17,
    tags: [
      "Pasta",
      "parmasean",
      "bacon",
      "cream",
      "egg",
      "mushroom",
      "parsley",
    ],
    preparationTime: 20,
    cookingTime: 15,
  },
  {
    id: 19,
    name: "Chicken and vegetable pie",
    url: "http://www.healthyfoodguide.com.au/recipes/2011/june/chicken-and-vegie-pie",
    pageNumber: 1,
    publicationId: 18,
    tags: ["Chicken", "mushroom", "pastry", "carrot", "leek"],
    preparationTime: 35,
    cookingTime: 30,
  },
  {
    id: 20,
    name: "Starch free bread",
    url: "https://docs.google.com/document/d/1GMmN1TTkzX08CUuvJ77Br2-nRza9AN3quJkrknu_f4g/edit?usp=sharing",
    pageNumber: 0,
    publicationId: 19,
    tags: ["bread starch-free"],
    preparationTime: 20,
    cookingTime: 90,
  },
  {
    id: 21,
    name: "Coconut ricotta hot cakes",
    url: "https://healthyrecipesblogs.com/2015/06/08/gluten-free-lemon-ricotta-pancakes",
    pageNumber: 0,
    publicationId: 20,
    tags: ["Coconut flour", "ricotta", "eggs", "lemon zest", "vanilla", "milk"],
    preparationTime: 10,
    cookingTime: 30,
  },
  {
    id: 22,
    name: "Beetroot & goat's cheese tart",
    pageNumber: 64,
    publicationId: 21,
    tags: [
      "Beetroot",
      "goats cheese",
      "thyme",
      "horseradish",
      "mustard",
      "red onion",
    ],
    preparationTime: 60,
    cookingTime: 120,
  },
];
